version: '3'
services:
  electron:
    container_name: electron-test
    build: ./
    environment:
      # - DISPLAY=host.docker.internal:0
      - DISPLAY=$DISPLAY:0
    network_mode: "host"
    volumes:
      - ./electron-quick-start:/home/app
      # - $HOME/.Xauthority:/root/.Xauthority
    tty: true
