version: '3'
services:
  app:
    container_name: test
    build:
      args:
        - USER_NAME
        - USER_ID
        - GROUP_NAME
        - GROUP_ID

    volumes:
      - ./:/mnt/work
    tty: true

# build command
# docker-compose build --build-arg USER_NAME=$(id -un) --build-arg USER_ID=$(id -u) --build-arg GROUP_NAME=$(id -gn) --build-arg GROUP_ID=$(id -g)
